[from-internal]
exten => _X.,1,NoOp(Call from ${CALLERID(num)} to ${EXTEN})
 same => n,Set(CALLER=${CALLERID(num)})
 same => n,Set(CALLED=${EXTEN})
 same => n,Stasis(call-controller)
 same => n,Hangup()